name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex

      - name: Rename PDF
        run: mv thesis.pdf built_thesis.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v6
        with:
          name: pdf
          path: built_thesis.pdf
